begin;

alter table public.user_profiles add column if not exists gamer_tag text;

create sequence if not exists public.community_request_number_seq;
create sequence if not exists public.community_report_number_seq;
create sequence if not exists public.community_feedback_number_seq;
create sequence if not exists public.user_story_number_seq;
create sequence if not exists public.bug_number_seq;

create table if not exists public.community_items (
  id bigint generated by default as identity primary key,
  public_id text unique,
  category text not null check (category in ('Request','Report','Feedback')),
  title text not null check (char_length(title) between 1 and 100),
  details text not null check (char_length(details) between 1 and 4000),
  submitted_by uuid not null default auth.uid() references auth.users(id),
  submitter_email text not null default coalesce(auth.jwt()->>'email','Unknown user'),
  source_feedback_id bigint unique,
  created_at timestamptz not null default now()
);

create table if not exists public.community_votes (
  community_item_id bigint not null references public.community_items(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  value smallint not null check (value in (-1,1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (community_item_id,user_id)
);

create table if not exists public.work_items (
  id bigint generated by default as identity primary key,
  public_id text unique,
  item_type text not null check (item_type in ('User Story','Bug')),
  title text not null check (char_length(title) between 1 and 140),
  description text not null check (char_length(description) between 1 and 6000),
  business_value text not null default '',
  acceptance_criteria text not null default '',
  story_size text not null default 'M' check (story_size in ('XS','S','M','L','XL')),
  priority text not null default 'Medium' check (priority in ('Low','Medium','High','Critical')),
  severity text check (severity is null or severity in ('Minor','Moderate','Major','Critical')),
  steps_to_reproduce text not null default '',
  expected_behavior text not null default '',
  actual_behavior text not null default '',
  status text not null default 'Backlog' check (status in ('Backlog','Accepted','Declined','In Progress','Review Pending','Complete')),
  created_by uuid not null default auth.uid() references auth.users(id),
  updated_by uuid not null default auth.uid() references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.work_item_community_links (
  work_item_id bigint not null references public.work_items(id) on delete cascade,
  community_item_id bigint not null references public.community_items(id) on delete cascade,
  primary key(work_item_id,community_item_id)
);

create or replace function public.assign_community_public_id()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.public_id is null then
    new.public_id := case new.category
      when 'Request' then 'WREQ-REQ-' || lpad(nextval('public.community_request_number_seq')::text,4,'0')
      when 'Report' then 'WREQ-REP-' || lpad(nextval('public.community_report_number_seq')::text,4,'0')
      else 'WREQ-FBK-' || lpad(nextval('public.community_feedback_number_seq')::text,4,'0') end;
  end if;
  return new;
end; $$;

drop trigger if exists assign_community_public_id_trigger on public.community_items;
create trigger assign_community_public_id_trigger before insert on public.community_items
for each row execute function public.assign_community_public_id();

create or replace function public.assign_work_item_public_id()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  if new.public_id is null then
    new.public_id := case new.item_type
      when 'Bug' then 'WREQ-BUG-' || lpad(nextval('public.bug_number_seq')::text,4,'0')
      else 'WREQ-US-' || lpad(nextval('public.user_story_number_seq')::text,4,'0') end;
  end if;
  new.updated_by := auth.uid();
  new.updated_at := now();
  return new;
end; $$;

drop trigger if exists assign_work_item_public_id_trigger on public.work_items;
create trigger assign_work_item_public_id_trigger before insert or update on public.work_items
for each row execute function public.assign_work_item_public_id();

insert into public.community_items(category,title,details,submitted_by,submitter_email,source_feedback_id,created_at)
select 'Request',subject,context,submitted_by,submitter_email,id,created_at from public.feedback
on conflict (source_feedback_id) do nothing;

alter table public.community_items enable row level security;
alter table public.community_votes enable row level security;
alter table public.work_items enable row level security;
alter table public.work_item_community_links enable row level security;

create policy "authenticated submit community items" on public.community_items for insert to authenticated
with check (submitted_by=auth.uid());
create policy "moderators read raw community items" on public.community_items for select to authenticated
using (public.can_moderate());
create policy "moderators delete community items" on public.community_items for delete to authenticated
using (public.can_moderate());

create policy "users manage own community votes" on public.community_votes for all to authenticated
using (user_id=auth.uid()) with check (user_id=auth.uid());

create policy "authenticated view work items" on public.work_items for select to authenticated using (true);
create policy "moderators insert work items" on public.work_items for insert to authenticated with check (public.can_moderate());
create policy "moderators update work items" on public.work_items for update to authenticated using (public.can_moderate()) with check (public.can_moderate());
create policy "moderators delete work items" on public.work_items for delete to authenticated using (public.can_moderate());

create policy "authenticated view work links" on public.work_item_community_links for select to authenticated using (true);
create policy "moderators manage work links" on public.work_item_community_links for all to authenticated
using (public.can_moderate()) with check (public.can_moderate());

create or replace function public.mask_archive_email(source_email text)
returns text language sql immutable as $$
  select case when position('@' in source_email)>0
    then left(split_part(source_email,'@',1),least(2,length(split_part(source_email,'@',1)))) || '*****@' || split_part(source_email,'@',2)
    else left(source_email,2) || '*****' end;
$$;

create or replace function public.get_community_items()
returns table(id bigint,public_id text,category text,title text,details text,submitted_by uuid,author_label text,submitter_email text,created_at timestamptz,upvotes bigint,downvotes bigint,net_score bigint,my_vote smallint,linked_work_items jsonb)
language sql stable security definer set search_path=public as $$
  select item.id,item.public_id,item.category,item.title,item.details,item.submitted_by,
    coalesce(nullif(profile.gamer_tag,''),public.mask_archive_email(item.submitter_email)) as author_label,
    case when public.can_moderate() then item.submitter_email else null end,
    item.created_at,
    count(vote.*) filter(where vote.value=1),count(vote.*) filter(where vote.value=-1),coalesce(sum(vote.value),0),
    max(vote.value) filter(where vote.user_id=auth.uid()),
    coalesce(jsonb_agg(distinct jsonb_build_object('id',work.public_id,'title',work.title)) filter(where work.id is not null),'[]'::jsonb)
  from public.community_items item
  left join public.user_profiles profile on profile.user_id=item.submitted_by
  left join public.community_votes vote on vote.community_item_id=item.id
  left join public.work_item_community_links link on link.community_item_id=item.id
  left join public.work_items work on work.id=link.work_item_id
  where auth.uid() is not null
  group by item.id,profile.gamer_tag;
$$;
revoke all on function public.get_community_items() from public;
grant execute on function public.get_community_items() to authenticated;

create or replace function public.set_community_vote(target_item_id bigint,new_value smallint)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if new_value not in (-1,0,1) then raise exception 'Invalid vote'; end if;
  if new_value=0 then delete from public.community_votes where community_item_id=target_item_id and user_id=auth.uid();
  else insert into public.community_votes(community_item_id,user_id,value) values(target_item_id,auth.uid(),new_value)
    on conflict(community_item_id,user_id) do update set value=excluded.value,updated_at=now(); end if;
end; $$;
grant execute on function public.set_community_vote(bigint,smallint) to authenticated;

create or replace function public.link_work_item_by_public_id(target_work_item_id bigint,target_community_public_id text)
returns void language plpgsql security definer set search_path=public as $$
declare community_id bigint;
begin
  if not public.can_moderate() then raise exception 'Moderator access is required'; end if;
  select id into community_id from public.community_items where upper(public_id)=upper(trim(target_community_public_id));
  if community_id is null then raise exception 'Community item not found'; end if;
  insert into public.work_item_community_links(work_item_id,community_item_id) values(target_work_item_id,community_id) on conflict do nothing;
end; $$;
grant execute on function public.link_work_item_by_public_id(bigint,text) to authenticated;

commit;
