begin;

create table if not exists public.match_audit_log (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  action text not null check (action in ('created','edited')),
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null default 'Unknown user',
  changed_fields jsonb not null default '{}'::jsonb,
  before_record jsonb,
  after_record jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists match_audit_log_created_at_idx on public.match_audit_log(created_at desc);
create index if not exists match_audit_log_match_id_idx on public.match_audit_log(match_id);

alter table public.match_audit_log enable row level security;

drop policy if exists "contributors view match audit history" on public.match_audit_log;
create policy "contributors view match audit history" on public.match_audit_log
for select to authenticated using (true);

create or replace function public.record_match_audit_event()
returns trigger
language plpgsql
security definer
set search_path=public
as $$
declare
  changes jsonb := '{}'::jsonb;
  user_email text := coalesce(auth.jwt()->>'email', 'Unknown user');
begin
  if tg_op = 'UPDATE' then
    if old.match_date is distinct from new.match_date then changes := changes || jsonb_build_object('date', jsonb_build_object('from',old.match_date,'to',new.match_date)); end if;
    if old.friend_group_size is distinct from new.friend_group_size then changes := changes || jsonb_build_object('party size', jsonb_build_object('from',old.friend_group_size,'to',new.friend_group_size)); end if;
    if old.ally_side is distinct from new.ally_side then changes := changes || jsonb_build_object('side', jsonb_build_object('from',old.ally_side,'to',new.ally_side)); end if;
    if old.result is distinct from new.result then changes := changes || jsonb_build_object('result', jsonb_build_object('from',old.result,'to',new.result)); end if;
    if old.duration_minutes is distinct from new.duration_minutes then changes := changes || jsonb_build_object('duration', jsonb_build_object('from',old.duration_minutes,'to',new.duration_minutes)); end if;
    if old.notes is distinct from new.notes then changes := changes || jsonb_build_object('notes', jsonb_build_object('from',old.notes,'to',new.notes)); end if;
  end if;

  insert into public.match_audit_log(match_id,action,actor_id,actor_email,changed_fields,before_record,after_record)
  values(new.id,case when tg_op='INSERT' then 'created' else 'edited' end,auth.uid(),user_email,changes,case when tg_op='UPDATE' then to_jsonb(old) else null end,to_jsonb(new));
  return new;
end;
$$;

drop trigger if exists matches_audit_trigger on public.matches;
create trigger matches_audit_trigger
after insert or update on public.matches
for each row execute function public.record_match_audit_event();

commit;
