begin;

create table if not exists public.pending_match_submissions (
  id bigint generated by default as identity primary key,
  submitted_by uuid not null references auth.users(id) on delete cascade,
  submitter_email text not null,
  match_data jsonb not null,
  performance_data jsonb not null,
  capture_metadata jsonb not null default '{}'::jsonb,
  external_capture_id text not null unique,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  rejection_reason text,
  created_at timestamptz not null default now()
);
create index if not exists pending_match_status_created_idx on public.pending_match_submissions(status,created_at desc);
alter table public.pending_match_submissions enable row level security;

drop policy if exists "users submit captured matches" on public.pending_match_submissions;
create policy "users submit captured matches" on public.pending_match_submissions for insert to authenticated
with check (submitted_by=auth.uid() and status='pending');
drop policy if exists "submitters and moderators view captured matches" on public.pending_match_submissions;
create policy "submitters and moderators view captured matches" on public.pending_match_submissions for select to authenticated
using (submitted_by=auth.uid() or public.can_moderate());

create or replace function public.submit_match_for_review(match_data jsonb,performance_data jsonb,capture_metadata jsonb,external_capture_id text)
returns bigint language plpgsql security definer set search_path=public as $$
declare submission_id bigint;
begin
  if auth.uid() is null then raise exception 'Authentication is required'; end if;
  insert into public.pending_match_submissions(submitted_by,submitter_email,match_data,performance_data,capture_metadata,external_capture_id)
  values(auth.uid(),coalesce(auth.jwt()->>'email','Unknown user'),match_data,performance_data,coalesce(capture_metadata,'{}'::jsonb),external_capture_id)
  on conflict (external_capture_id) do nothing returning id into submission_id;
  if submission_id is null then select id into submission_id from public.pending_match_submissions p where p.external_capture_id=submit_match_for_review.external_capture_id and p.submitted_by=auth.uid(); end if;
  if submission_id is null then raise exception 'Capture ID is already registered by another account'; end if;
  return submission_id;
end;
$$;
grant execute on function public.submit_match_for_review(jsonb,jsonb,jsonb,text) to authenticated;

create or replace function public.approve_pending_match(target_submission_id bigint,revised_match_data jsonb,revised_performance_data jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare submission public.pending_match_submissions%rowtype; new_id bigint; item jsonb;
begin
  if not public.can_moderate() then raise exception 'Moderator or Administrator access is required'; end if;
  select * into submission from public.pending_match_submissions where id=target_submission_id and status='pending' for update;
  if not found then raise exception 'Pending submission was not found'; end if;
  perform pg_advisory_xact_lock(7242026);
  select coalesce(max(id),0)+1 into new_id from public.matches;
  insert into public.matches(id,match_date,friend_group_size,ally_side,result,duration_minutes,notes,created_by)
  values(new_id,(revised_match_data->>'match_date')::date,(revised_match_data->>'friend_group_size')::int,revised_match_data->>'ally_side',revised_match_data->>'result',(revised_match_data->>'duration_minutes')::numeric,coalesce(revised_match_data->>'notes',''),submission.submitted_by);
  for item in select * from jsonb_array_elements(revised_performance_data) loop
    insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision,created_by)
    values(new_id,'Ally',true,item->>'player',item->>'champion',item->>'role',(item->>'kills')::int,(item->>'deaths')::int,(item->>'assists')::int,(item->>'cs')::int,(item->>'vision')::int,submission.submitted_by);
  end loop;
  update public.pending_match_submissions set status='approved',match_data=revised_match_data,performance_data=revised_performance_data,reviewed_by=auth.uid(),reviewed_at=now() where id=target_submission_id;
  return new_id;
end;
$$;
grant execute on function public.approve_pending_match(bigint,jsonb,jsonb) to authenticated;

create or replace function public.reject_pending_match(target_submission_id bigint,reason text default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.can_moderate() then raise exception 'Moderator or Administrator access is required'; end if;
  update public.pending_match_submissions set status='rejected',rejection_reason=nullif(trim(reason),''),reviewed_by=auth.uid(),reviewed_at=now() where id=target_submission_id and status='pending';
  if not found then raise exception 'Pending submission was not found'; end if;
end;
$$;
grant execute on function public.reject_pending_match(bigint,text) to authenticated;

commit;
