begin;

create table if not exists public.players (
  name text primary key,
  created_at timestamptz not null default now()
);
create table if not exists public.champions (
  name text primary key,
  created_at timestamptz not null default now()
);
create table if not exists public.roles (
  name text primary key,
  created_at timestamptz not null default now()
);
create table if not exists public.matches (
  id bigint primary key,
  match_date date not null,
  friend_group_size integer not null check (friend_group_size between 1 and 5),
  ally_side text not null check (ally_side in ('Blue','Purple')),
  result text not null check (result in ('Win','Loss')),
  duration_minutes numeric(6,2) not null check (duration_minutes > 0),
  notes text not null default '',
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create table if not exists public.performances (
  id bigint generated by default as identity primary key,
  match_id bigint not null references public.matches(id) on delete cascade,
  team text not null default 'Ally',
  tracked boolean not null default true,
  player text not null references public.players(name),
  champion text not null references public.champions(name),
  role text not null references public.roles(name),
  kills integer not null check (kills >= 0),
  deaths integer not null check (deaths >= 0),
  assists integer not null check (assists >= 0),
  cs integer not null check (cs >= 0),
  vision integer not null check (vision >= 0),
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now()
);
create index if not exists performances_match_id_idx on public.performances(match_id);
create index if not exists performances_player_idx on public.performances(player);
create index if not exists matches_date_idx on public.matches(match_date desc);

alter table public.players enable row level security;
alter table public.champions enable row level security;
alter table public.roles enable row level security;
alter table public.matches enable row level security;
alter table public.performances enable row level security;

drop policy if exists "reference lists are public" on public.players;
create policy "reference lists are public" on public.players for select to anon, authenticated using (true);
drop policy if exists "champions are public" on public.champions;
create policy "champions are public" on public.champions for select to anon, authenticated using (true);
drop policy if exists "roles are public" on public.roles;
create policy "roles are public" on public.roles for select to anon, authenticated using (true);
drop policy if exists "matches are public" on public.matches;
create policy "matches are public" on public.matches for select to anon, authenticated using (true);
drop policy if exists "performances are public" on public.performances;
create policy "performances are public" on public.performances for select to anon, authenticated using (true);
drop policy if exists "authenticated users add matches" on public.matches;
create policy "authenticated users add matches" on public.matches for insert to authenticated with check ((select auth.uid()) = created_by);
drop policy if exists "owners update matches" on public.matches;
create policy "owners update matches" on public.matches for update to authenticated using ((select auth.uid()) = created_by) with check ((select auth.uid()) = created_by);
drop policy if exists "owners delete matches" on public.matches;
create policy "owners delete matches" on public.matches for delete to authenticated using ((select auth.uid()) = created_by);
drop policy if exists "authenticated users add performances" on public.performances;
create policy "authenticated users add performances" on public.performances for insert to authenticated with check ((select auth.uid()) = created_by);
drop policy if exists "owners update performances" on public.performances;
create policy "owners update performances" on public.performances for update to authenticated using ((select auth.uid()) = created_by) with check ((select auth.uid()) = created_by);
drop policy if exists "owners delete performances" on public.performances;
create policy "owners delete performances" on public.performances for delete to authenticated using ((select auth.uid()) = created_by);

insert into public.players(name) values ('Dane'),('Jake'),('Kaleb'),('Blake D.'),('Blake G.'),('Austin'),('Rachel'),('Zach'),('Steven') on conflict do nothing;
insert into public.champions(name) values ('Ahri'),('Alistar'),('Amumu'),('Anivia'),('Annie'),('Ashe'),('Blitzcrank'),('Brand'),('Cho''Gath'),('Corki'),('Dr. Mundo'),('Evelynn'),('Ezreal'),('Fiddlesticks'),('Gangplank'),('Garen'),('Gragas'),('Graves'),('Heimerdinger'),('Janna'),('Jarvan IV'),('Jax'),('Karthus'),('Kassadin'),('Katarina'),('Kayle'),('Kog''Maw'),('Lee Sin'),('Leona'),('Lulu'),('Lux'),('Malphite'),('Malzahar'),('Master Yi'),('Miss Fortune'),('Morgana'),('Nasus'),('Nidalee'),('Nunu'),('Olaf'),('Pantheon'),('Rammus'),('Ryze'),('Shaco'),('Singed'),('Sion'),('Sivir'),('Skarner'),('Sona'),('Soraka'),('Taric'),('Teemo'),('Tristana'),('Tryndamere'),('Twisted Fate'),('Twitch'),('Urgot'),('Vayne'),('Veigar'),('Warwick'),('Wukong'),('Zilean') on conflict do nothing;
insert into public.roles(name) values ('Top'),('Jungle'),('Mid'),('Bot'),('Support') on conflict do nothing;
insert into public.matches(id,match_date,friend_group_size,ally_side,result,duration_minutes,notes) values
(1,'2026-07-29',1,'Purple','Loss',39.5,'Spectated this one. Blake''s Lux and Eve fed hard.'),
(2,'2026-07-29',1,'Blue','Loss',36.4,'Only watched about half of this one. Winning hard, then lost?'),
(3,'2026-07-29',2,'Purple','Win',28.7,'First game. Absolute stomp.'),
(4,'2026-07-29',3,'Blue','Loss',60.3,'Wow. Long ass game. We lost, but it was a lot of fun anyway.'),
(5,'2026-07-29',4,'Blue','Win',21.2,'Surrender at 20.'),
(6,'2026-07-29',4,'Purple','Loss',30.7,'Rough one. Did fine, but got beat to death by the warwick. Ban WW?'),
(7,'2026-07-29',3,'Blue','Win',18.1,'Ezreal felt pretty busted.'),
(8,'2026-07-30',1,'Purple','Loss',19.7,'Ezreal solo. 3/1/1 but every lane lost.'),
(9,'2026-07-30',2,'Purple','Win',19.4,'MF dominance, but Blake carried on Malz.'),
(10,'2026-07-30',1,'Purple','Loss',31.9,'Ashe solo. Probably worst performance so far.'),
(11,'2026-07-30',5,'Purple','Win',30.6,'5 stack with a fed Kat on enemy side, but we won.'),
(12,'2026-07-30',5,'Purple','Win',26.3,'Pax Sivir. Got compliments.'),
(13,'2026-07-30',5,'Blue','Loss',33.1,'Kog''Maw. Really good Corki on enemy team.'),
(14,'2026-07-31',1,'Purple','Win',27.6,'Heimer is really fun. Deceptive damage.'),
(15,'2026-07-31',5,'Blue','Win',15.4,'Heimer again. 6/0 bby.'),
(16,'2026-07-31',5,'Purple','Win',43.2,'Heimer again. He''s really strong.'),
(17,'2026-07-31',2,'Blue','Win',27,'Johby/Austin game. Nice.'),
(18,'2026-07-31',3,'Blue','Win',43.7,'Ezreal bby. Shaco mid?'),
(19,'2026-07-31',4,'Blue','Win',45.2,'Jake, Rachel, Zach, Blake D. game. Parallel gaming because too many ppl. Good times.'),
(20,'2026-07-31',3,'Purple','Loss',34.8,'Heimer first loss. Sad.'),
(21,'2026-07-31',4,'Blue','Loss',25.9,'Jake, Rachel, Zach, Blake D. game. Second parallel of the night.'),
(22,'2026-08-01',1,'Blue','Win',36.8,'Blake D. solo game as Ashe.'),
(23,'2026-08-01',1,'Blue','Loss',20.8,'Blake D. solo game'),
(24,'2026-08-01',3,'Purple','Win',37.3,'Rachel/Jake/Dane. Ryze mid. Definitely ban WW, he was a menace.'),
(25,'2026-08-01',5,'Purple','Win',35.2,'Heimer with the full group.'),
(26,'2026-08-01',4,'Blue','Win',37.4,'Pool Party Heimer'),
(27,'2026-08-01',1,'Purple','Win',18.7,'Ashe solo. Their lee sin jungler rage quit at around 10 mins.'),
(28,'2026-08-01',3,'Blue','Loss',23.5,'Ezreal. Rachel on Teemo, Jake on Amumu. Soraka spammed starcall constantly, blamed Amumu for the fiddle mid going 0/10.'),
(29,'2026-08-01',4,'Purple','Win',15.8,'Heimer v. Kassadin mid. Proving once again that Kassadin is not Kassawin.'),
(30,'2026-08-01',4,'Blue','Loss',42.6,'Heimer loss. Malzahar big problem, Skarner too.'),
(31,'2026-08-02',3,'Purple','Win',29.7,'Dominant game. Enemy team took no objectives.'),
(32,'2026-08-02',4,'Blue','Win',37.6,'Karthus mid. Went fine in lane, but took a while to scale.'),
(33,'2026-08-02',1,'Blue','Loss',31.6,'Blake D. solo top Ryze.'),
(34,'2026-08-02',3,'Purple','Win',16.5,'Bullied the Ahri mid as Heimer and she quit.'),
(35,'2026-08-02',3,'Blue','Win',18.5,'First time seeing Annie. She was cheeks.'),
(36,'2026-08-02',2,'Purple','Loss',32,'Zach and Blake K. duo game. Enemy Eve 16/1. Crazy.')
on conflict (id) do update set match_date=excluded.match_date,friend_group_size=excluded.friend_group_size,ally_side=excluded.ally_side,result=excluded.result,duration_minutes=excluded.duration_minutes,notes=excluded.notes;
delete from public.performances where match_id between 1 and 36 and created_by is null;
insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision) values
(1,'Ally',true,'Blake D.','Pantheon','Support',4,7,12,52,21),
(2,'Ally',true,'Blake D.','Ezreal','Bot',9,4,9,215,5),
(3,'Ally',true,'Blake D.','Blitzcrank','Support',2,3,16,23,27),
(3,'Ally',true,'Dane','Corki','Bot',7,2,12,176,2),
(4,'Ally',true,'Blake D.','Leona','Support',6,13,39,40,25),
(4,'Ally',true,'Dane','Ryze','Mid',20,11,13,324,8),
(4,'Ally',true,'Jake','Warwick','Jungle',12,10,13,206,7),
(5,'Ally',true,'Dane','Ashe','Bot',5,1,4,129,14),
(5,'Ally',true,'Zach','Leona','Support',1,0,6,2,27),
(5,'Ally',true,'Austin','Dr. Mundo','Top',0,5,2,67,5),
(5,'Ally',true,'Kaleb','Warwick','Jungle',1,0,7,90,4),
(6,'Ally',true,'Dane','Miss Fortune','Bot',13,8,8,193,5),
(6,'Ally',true,'Zach','Leona','Support',3,5,14,14,26),
(6,'Ally',true,'Blake G.','Gragas','Mid',3,6,9,142,11),
(6,'Ally',true,'Austin','Nasus','Top',1,6,2,112,5),
(6,'Ally',true,'Jake','Master Yi','Jungle',9,8,10,116,5),
(7,'Ally',true,'Dane','Ezreal','Bot',5,1,9,99,2),
(7,'Ally',true,'Zach','Amumu','Jungle',5,2,7,76,2),
(7,'Ally',true,'Blake G.','Blitzcrank','Support',3,2,6,3,11),
(8,'Ally',true,'Dane','Ezreal','Bot',3,1,1,105,2),
(9,'Ally',true,'Blake D.','Malzahar','Mid',10,0,4,116,9),
(9,'Ally',true,'Dane','Miss Fortune','Bot',5,3,9,113,1),
(10,'Ally',true,'Dane','Ashe','Bot',3,4,5,178,2),
(11,'Ally',true,'Dane','Ashe','Bot',8,4,9,144,10),
(11,'Ally',true,'Blake D.','Evelynn','Jungle',16,5,3,108,0),
(11,'Ally',true,'Zach','Leona','Support',3,4,15,22,39),
(11,'Ally',true,'Austin','Malphite','Top',3,8,13,99,4),
(11,'Ally',true,'Kaleb','Ahri','Mid',4,5,5,161,3),
(12,'Ally',true,'Dane','Sivir','Bot',4,2,12,139,1),
(12,'Ally',true,'Blake D.','Fiddlesticks','Jungle',13,1,9,126,0),
(12,'Ally',true,'Zach','Leona','Support',4,1,11,12,21),
(12,'Ally',true,'Austin','Malphite','Top',2,4,3,80,4),
(12,'Ally',true,'Kaleb','Morgana','Mid',4,4,9,158,2),
(13,'Ally',true,'Dane','Kog''Maw','Bot',12,12,14,175,2),
(13,'Ally',true,'Blake D.','Nunu','Jungle',5,7,18,117,11),
(13,'Ally',true,'Zach','Leona','Support',4,6,19,21,30),
(13,'Ally',true,'Austin','Malphite','Top',2,11,6,75,5),
(13,'Ally',true,'Kaleb','Veigar','Mid',16,7,8,168,1),
(14,'Ally',true,'Dane','Heimerdinger','Mid',4,2,6,147,9),
(15,'Ally',true,'Dane','Heimerdinger','Top',6,0,0,116,4),
(15,'Ally',true,'Blake D.','Malzahar','Mid',4,1,0,117,2),
(15,'Ally',true,'Rachel','Miss Fortune','Bot',1,0,3,46,0),
(15,'Ally',true,'Jake','Jarvan IV','Jungle',3,1,2,60,7),
(15,'Ally',true,'Zach','Leona','Support',0,0,4,13,6),
(16,'Ally',true,'Blake D.','Gangplank','Top',9,4,17,342,5),
(16,'Ally',true,'Dane','Heimerdinger','Mid',19,9,8,272,2),
(16,'Ally',true,'Jake','Amumu','Jungle',3,9,18,148,9),
(16,'Ally',true,'Rachel','Sivir','Bot',7,5,17,175,4),
(16,'Ally',true,'Zach','Leona','Support',4,8,18,35,47),
(17,'Ally',true,'Austin','Miss Fortune','Bot',2,7,12,88,2),
(17,'Ally',true,'Kaleb','Amumu','Jungle',3,1,12,119,1),
(18,'Ally',true,'Dane','Ezreal','Bot',14,3,13,281,3),
(18,'Ally',true,'Kaleb','Sona','Support',2,4,24,19,61),
(18,'Ally',true,'Austin','Ahri','Mid',6,11,11,99,6),
(19,'Ally',true,'Zach','Leona','Support',3,4,21,20,45),
(19,'Ally',true,'Blake D.','Kayle','Top',19,5,7,300,6),
(19,'Ally',true,'Jake','Cho''Gath','Jungle',9,1,15,167,6),
(19,'Ally',true,'Rachel','Miss Fortune','Bot',4,8,9,153,4),
(20,'Ally',true,'Dane','Heimerdinger','Mid',5,5,4,205,4),
(20,'Ally',true,'Austin','Leona','Support',1,8,5,12,31),
(20,'Ally',true,'Kaleb','Ezreal','Bot',4,6,2,211,1),
(21,'Ally',true,'Jake','Lee Sin','Jungle',3,6,2,89,6),
(21,'Ally',true,'Rachel','Miss Fortune','Bot',0,5,1,85,0),
(21,'Ally',true,'Zach','Leona','Support',0,2,6,14,18),
(21,'Ally',true,'Blake D.','Pantheon','Top',3,3,0,122,1),
(22,'Ally',true,'Blake D.','Ashe','Bot',11,9,17,190,10),
(23,'Ally',true,'Blake D.','Kog''Maw','Bot',3,3,1,103,2),
(24,'Ally',true,'Jake','Jarvan IV','Jungle',8,2,16,25,12),
(24,'Ally',true,'Rachel','Miss Fortune','Bot',7,5,10,175,6),
(24,'Ally',true,'Dane','Ryze','Mid',2,3,9,152,5),
(25,'Ally',true,'Rachel','Fiddlesticks','Bot',3,7,9,83,1),
(25,'Ally',true,'Zach','Leona','Support',7,2,15,51,25),
(25,'Ally',true,'Dane','Heimerdinger','Mid',7,5,5,242,4),
(25,'Ally',true,'Blake D.','Warwick','Jungle',18,2,9,157,12),
(25,'Ally',true,'Jake','Sion','Top',3,6,7,170,6),
(26,'Ally',true,'Dane','Heimerdinger','Mid',7,5,10,215,5),
(26,'Ally',true,'Rachel','Sivir','Bot',2,6,10,161,4),
(26,'Ally',true,'Jake','Fiddlesticks','Support',6,8,8,45,10),
(26,'Ally',true,'Blake D.','Wukong','Jungle',11,2,9,184,11),
(27,'Ally',true,'Dane','Ashe','Bot',1,0,2,145,2),
(28,'Ally',true,'Dane','Ezreal','Bot',4,2,0,132,1),
(28,'Ally',true,'Rachel','Teemo','Top',0,0,0,121,1),
(28,'Ally',true,'Jake','Amumu','Jungle',0,2,0,100,7),
(29,'Ally',true,'Blake D.','Ryze','Top',7,0,2,91,6),
(29,'Ally',true,'Rachel','Sivir','Bot',1,3,2,56,3),
(29,'Ally',true,'Jake','Taric','Support',0,1,3,15,2),
(29,'Ally',true,'Dane','Heimerdinger','Mid',2,2,2,107,1),
(30,'Ally',true,'Dane','Heimerdinger','Mid',7,7,5,242,4),
(30,'Ally',true,'Jake','Jarvan IV','Jungle',6,10,9,137,12),
(30,'Ally',true,'Blake D.','Ryze','Top',14,8,5,261,12),
(30,'Ally',true,'Rachel','Sivir','Bot',3,10,11,209,5),
(31,'Ally',true,'Dane','Heimerdinger','Mid',6,4,10,152,11),
(31,'Ally',true,'Kaleb','Dr. Mundo','Top',4,0,2,219,2),
(31,'Ally',true,'Blake D.','Jarvan IV','Jungle',3,0,9,153,6),
(32,'Ally',true,'Zach','Morgana','Support',3,10,16,27,47),
(32,'Ally',true,'Kaleb','Dr. Mundo','Top',3,6,8,245,0),
(32,'Ally',true,'Blake D.','Sivir','Bot',18,6,9,259,8),
(32,'Ally',true,'Dane','Karthus','Mid',5,7,15,220,3),
(33,'Ally',true,'Blake D.','Ryze','Top',7,7,7,159,7),
(34,'Ally',true,'Dane','Heimerdinger','Mid',3,1,3,99,8),
(34,'Ally',true,'Zach','Leona','Support',1,1,4,1,10),
(34,'Ally',true,'Blake D.','Kog''Maw','Bot',4,2,2,97,2),
(35,'Ally',true,'Zach','Leona','Support',1,1,5,7,13),
(35,'Ally',true,'Blake D.','Twitch','Bot',9,2,1,119,2),
(35,'Ally',true,'Dane','Heimerdinger','Mid',2,0,1,130,15),
(36,'Ally',true,'Blake D.','Ezreal','Bot',7,6,8,176,7),
(36,'Ally',true,'Zach','Amumu','Jungle',3,3,14,103,11);

create or replace function public.create_match_with_performances(match_data jsonb, performance_data jsonb)
returns bigint language plpgsql security invoker set search_path=public as $$
declare new_id bigint; item jsonb;
begin
  select coalesce(max(id),0)+1 into new_id from public.matches;
  insert into public.matches(id,match_date,friend_group_size,ally_side,result,duration_minutes,notes,created_by)
  values(new_id,(match_data->>'match_date')::date,(match_data->>'friend_group_size')::int,match_data->>'ally_side',match_data->>'result',(match_data->>'duration_minutes')::numeric,coalesce(match_data->>'notes',''),auth.uid());
  for item in select * from jsonb_array_elements(performance_data) loop
    insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision,created_by)
    values(new_id,'Ally',true,item->>'player',item->>'champion',item->>'role',(item->>'kills')::int,(item->>'deaths')::int,(item->>'assists')::int,(item->>'cs')::int,(item->>'vision')::int,auth.uid());
  end loop;
  return new_id;
end; $$;
grant execute on function public.create_match_with_performances(jsonb,jsonb) to authenticated;

select setval(pg_get_serial_sequence('public.performances','id'),coalesce((select max(id) from public.performances),1));
commit;