begin;

create table if not exists public.performance_items (
  id bigint generated by default as identity primary key,
  performance_id bigint not null references public.performances(id) on delete cascade,
  item_id integer not null check (item_id > 0),
  slot smallint not null check (slot between 0 and 6),
  quantity integer not null default 1 check (quantity > 0),
  captured_name text,
  created_at timestamptz not null default now(),
  unique(performance_id,slot)
);
create index if not exists performance_items_performance_idx on public.performance_items(performance_id);
create index if not exists performance_items_item_idx on public.performance_items(item_id);

alter table public.performance_items enable row level security;
drop policy if exists "anyone views final inventories" on public.performance_items;
create policy "anyone views final inventories" on public.performance_items for select to anon,authenticated using (true);
drop policy if exists "owners and moderators insert final inventories" on public.performance_items;
create policy "owners and moderators insert final inventories" on public.performance_items for insert to authenticated
with check (exists(select 1 from public.performances p where p.id=performance_id and (p.created_by=auth.uid() or public.can_moderate())));
drop policy if exists "owners and moderators delete final inventories" on public.performance_items;
create policy "owners and moderators delete final inventories" on public.performance_items for delete to authenticated
using (exists(select 1 from public.performances p where p.id=performance_id and (p.created_by=auth.uid() or public.can_moderate())));
grant select on public.performance_items to anon,authenticated;
grant insert,delete on public.performance_items to authenticated;
grant usage,select on sequence public.performance_items_id_seq to authenticated;

create or replace function public.create_match_with_performances(match_data jsonb, performance_data jsonb)
returns bigint language plpgsql security invoker set search_path=public as $$
declare new_id bigint; item jsonb; inventory_item jsonb; new_performance_id bigint; requested_game_id text;
begin
  requested_game_id=nullif(btrim(match_data->>'game_id'),'');
  if requested_game_id is null then raise exception 'Game ID is required'; end if;
  perform pg_advisory_xact_lock(7242026);
  if exists(select 1 from public.matches where game_id=requested_game_id) then raise exception 'Game ID % already exists in the archive',requested_game_id; end if;
  select coalesce(max(id),0)+1 into new_id from public.matches;
  insert into public.matches(id,game_id,match_date,friend_group_size,ally_side,result,duration_minutes,notes,created_by)
  values(new_id,requested_game_id,(match_data->>'match_date')::date,(match_data->>'friend_group_size')::int,match_data->>'ally_side',match_data->>'result',(match_data->>'duration_minutes')::numeric,coalesce(match_data->>'notes',''),auth.uid());
  for item in select * from jsonb_array_elements(performance_data) loop
    insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision,created_by)
    values(new_id,'Ally',true,item->>'player',item->>'champion',item->>'role',(item->>'kills')::int,(item->>'deaths')::int,(item->>'assists')::int,(item->>'cs')::int,(item->>'vision')::int,auth.uid())
    returning id into new_performance_id;
    for inventory_item in select * from jsonb_array_elements(coalesce(item->'items','[]'::jsonb)) loop
      insert into public.performance_items(performance_id,item_id,slot,quantity,captured_name)
      values(new_performance_id,(inventory_item->>'item_id')::int,(inventory_item->>'slot')::smallint,coalesce((inventory_item->>'quantity')::int,1),nullif(inventory_item->>'captured_name',''));
    end loop;
  end loop;
  return new_id;
end; $$;

create or replace function public.update_match_with_performances(target_match_id bigint, match_data jsonb, performance_data jsonb)
returns bigint language plpgsql security invoker set search_path=public as $$
declare item jsonb; inventory_item jsonb; inventory_source jsonb; prior_inventories jsonb; new_performance_id bigint; requested_game_id text;
begin
  requested_game_id=nullif(btrim(match_data->>'game_id'),'');
  if requested_game_id is null then raise exception 'Game ID is required'; end if;
  if exists(select 1 from public.matches where game_id=requested_game_id and id<>target_match_id) then raise exception 'Game ID % already exists in the archive',requested_game_id; end if;
  update public.matches set game_id=requested_game_id,match_date=(match_data->>'match_date')::date,friend_group_size=(match_data->>'friend_group_size')::int,ally_side=match_data->>'ally_side',result=match_data->>'result',duration_minutes=(match_data->>'duration_minutes')::numeric,notes=coalesce(match_data->>'notes','') where id=target_match_id;
  if not found then raise exception 'Match % was not found', target_match_id; end if;
  select coalesce(jsonb_agg(jsonb_build_object('player',p.player,'champion',p.champion,'items',coalesce((select jsonb_agg(jsonb_build_object('item_id',pi.item_id,'slot',pi.slot,'quantity',pi.quantity,'captured_name',pi.captured_name) order by pi.slot) from public.performance_items pi where pi.performance_id=p.id),'[]'::jsonb))),'[]'::jsonb)
  into prior_inventories from public.performances p where p.match_id=target_match_id;
  delete from public.performances where match_id=target_match_id;
  for item in select * from jsonb_array_elements(performance_data) loop
    insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision,created_by)
    values(target_match_id,'Ally',true,item->>'player',item->>'champion',item->>'role',(item->>'kills')::int,(item->>'deaths')::int,(item->>'assists')::int,(item->>'cs')::int,(item->>'vision')::int,auth.uid())
    returning id into new_performance_id;
    inventory_source=item->'items';
    if inventory_source is null or jsonb_array_length(inventory_source)=0 then
      select saved->'items' into inventory_source from jsonb_array_elements(prior_inventories) saved where saved->>'player'=item->>'player' and saved->>'champion'=item->>'champion' limit 1;
    end if;
    for inventory_item in select * from jsonb_array_elements(coalesce(inventory_source,'[]'::jsonb)) loop
      insert into public.performance_items(performance_id,item_id,slot,quantity,captured_name)
      values(new_performance_id,(inventory_item->>'item_id')::int,(inventory_item->>'slot')::smallint,coalesce((inventory_item->>'quantity')::int,1),nullif(inventory_item->>'captured_name',''));
    end loop;
  end loop;
  return target_match_id;
end; $$;

create or replace function public.approve_pending_match(target_submission_id bigint,revised_match_data jsonb,revised_performance_data jsonb)
returns bigint language plpgsql security definer set search_path=public as $$
declare submission public.pending_match_submissions%rowtype; new_id bigint; item jsonb; inventory_item jsonb; inventory_source jsonb; new_performance_id bigint; requested_game_id text;
begin
  if not public.can_moderate() then raise exception 'Moderator or Administrator access is required'; end if;
  select * into submission from public.pending_match_submissions where id=target_submission_id and status='pending' for update;
  if not found then raise exception 'Pending submission was not found'; end if;
  requested_game_id=nullif(btrim(revised_match_data->>'game_id'),'');
  if requested_game_id is null then raise exception 'Game ID is required'; end if;
  perform pg_advisory_xact_lock(7242026);
  if exists(select 1 from public.matches where game_id=requested_game_id) then raise exception 'Game ID % already exists in the archive',requested_game_id; end if;
  select coalesce(max(id),0)+1 into new_id from public.matches;
  insert into public.matches(id,game_id,match_date,friend_group_size,ally_side,result,duration_minutes,notes,created_by)
  values(new_id,requested_game_id,(revised_match_data->>'match_date')::date,(revised_match_data->>'friend_group_size')::int,revised_match_data->>'ally_side',revised_match_data->>'result',(revised_match_data->>'duration_minutes')::numeric,coalesce(revised_match_data->>'notes',''),submission.submitted_by);
  for item in select * from jsonb_array_elements(revised_performance_data) loop
    insert into public.performances(match_id,team,tracked,player,champion,role,kills,deaths,assists,cs,vision,created_by)
    values(new_id,'Ally',true,item->>'player',item->>'champion',item->>'role',(item->>'kills')::int,(item->>'deaths')::int,(item->>'assists')::int,(item->>'cs')::int,(item->>'vision')::int,submission.submitted_by)
    returning id into new_performance_id;
    inventory_source=item->'items';
    if inventory_source is null or jsonb_array_length(inventory_source)=0 then
      select captured->'items' into inventory_source from jsonb_array_elements(coalesce(submission.capture_metadata->'final_inventories','[]'::jsonb)) captured where captured->>'player'=item->>'player' limit 1;
    end if;
    for inventory_item in select * from jsonb_array_elements(coalesce(inventory_source,'[]'::jsonb)) loop
      insert into public.performance_items(performance_id,item_id,slot,quantity,captured_name)
      values(new_performance_id,(inventory_item->>'item_id')::int,(inventory_item->>'slot')::smallint,coalesce((inventory_item->>'quantity')::int,1),nullif(inventory_item->>'captured_name',''));
    end loop;
  end loop;
  update public.pending_match_submissions set status='approved',match_data=revised_match_data,performance_data=revised_performance_data,reviewed_by=auth.uid(),reviewed_at=now() where id=target_submission_id;
  return new_id;
end; $$;

grant execute on function public.create_match_with_performances(jsonb,jsonb) to authenticated;
grant execute on function public.update_match_with_performances(bigint,jsonb,jsonb) to authenticated;
grant execute on function public.approve_pending_match(bigint,jsonb,jsonb) to authenticated;

commit;
