begin;

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  subject text not null check (char_length(subject) between 1 and 100),
  context text not null check (char_length(context) between 1 and 1000),
  status text not null default 'REVIEW' check (status in ('REVIEW')),
  submitted_by uuid not null default auth.uid() references auth.users(id),
  submitter_email text not null default coalesce(auth.jwt()->>'email','Unknown user'),
  created_at timestamptz not null default now()
);

alter table public.feedback enable row level security;

drop policy if exists "authenticated users submit feedback" on public.feedback;
create policy "authenticated users submit feedback" on public.feedback
for insert to authenticated
with check (submitted_by=auth.uid() and status='REVIEW');

drop policy if exists "moderators review feedback" on public.feedback;
create policy "moderators review feedback" on public.feedback
for select to authenticated
using (public.can_moderate());

commit;
